Run test wp-env

diff --git a/.github/workflows/smoke-test-daily.yml b/.github/workflows/smoke-test-daily.yml
--- a/.github/workflows/smoke-test-daily.yml
+++ b/.github/workflows/smoke-test-daily.yml
@@ -128,54 +128,54 @@ jobs:
     #               retention-days: 5
 
     # k6-tests:
-        # name: k6 tests on nightly build
-        # runs-on: ubuntu-20.04
-        # permissions:
-        #     contents: read
-        # needs: [api-tests]
-        # if: success() || failure()
-        # steps:
-        #     - uses: actions/checkout@v3
+    # name: k6 tests on nightly build
+    # runs-on: ubuntu-20.04
+    # permissions:
+    #     contents: read
+    # needs: [api-tests]
+    # if: success() || failure()
+    # steps:
+    #     - uses: actions/checkout@v3
 
-        #     - name: Setup WooCommerce Monorepo
-        #       uses: ./.github/actions/setup-woocommerce-monorepo
-        #       with:
-        #           install-filters: woocommerce
-        #           build: false
+    #     - name: Setup WooCommerce Monorepo
+    #       uses: ./.github/actions/setup-woocommerce-monorepo
+    #       with:
+    #           install-filters: woocommerce
+    #           build: false
 
-        #     - name: Download and install Chromium browser.
-        #       working-directory: plugins/woocommerce
-        #       run: pnpm exec playwright install chromium
+    #     - name: Download and install Chromium browser.
+    #       working-directory: plugins/woocommerce
+    #       run: pnpm exec playwright install chromium
 
-        #     - name: Update performance test site with E2E test
-        #       working-directory: plugins/woocommerce
-        #       env:
-        #           BASE_URL: ${{ secrets.SMOKE_TEST_PERF_URL }}/
-        #           ADMIN_USER: ${{ secrets.SMOKE_TEST_PERF_ADMIN_USER }}
-        #           ADMIN_PASSWORD: ${{ secrets.SMOKE_TEST_PERF_ADMIN_PASSWORD }}
-        #           CUSTOMER_USER: ${{ secrets.SMOKE_TEST_PERF_ADMIN_USER }}
-        #           CUSTOMER_PASSWORD: ${{ secrets.SMOKE_TEST_PERF_ADMIN_PASSWORD }}
-        #           UPDATE_WC: nightly
-        #           DEFAULT_TIMEOUT_OVERRIDE: 120000
-        #       run: |
-        #           pnpm exec playwright test --config=tests/e2e-pw/playwright.config.js update-woocommerce.spec.js
-        #       continue-on-error: true
+    #     - name: Update performance test site with E2E test
+    #       working-directory: plugins/woocommerce
+    #       env:
+    #           BASE_URL: ${{ secrets.SMOKE_TEST_PERF_URL }}/
+    #           ADMIN_USER: ${{ secrets.SMOKE_TEST_PERF_ADMIN_USER }}
+    #           ADMIN_PASSWORD: ${{ secrets.SMOKE_TEST_PERF_ADMIN_PASSWORD }}
+    #           CUSTOMER_USER: ${{ secrets.SMOKE_TEST_PERF_ADMIN_USER }}
+    #           CUSTOMER_PASSWORD: ${{ secrets.SMOKE_TEST_PERF_ADMIN_PASSWORD }}
+    #           UPDATE_WC: nightly
+    #           DEFAULT_TIMEOUT_OVERRIDE: 120000
+    #       run: |
+    #           pnpm exec playwright test --config=tests/e2e-pw/playwright.config.js update-woocommerce.spec.js
+    #       continue-on-error: true
 
-        #     - name: Install k6
-        #       run: |
-        #           curl https://github.com/grafana/k6/releases/download/v0.33.0/k6-v0.33.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
+    #     - name: Install k6
+    #       run: |
+    #           curl https://github.com/grafana/k6/releases/download/v0.33.0/k6-v0.33.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
 
-        #     - name: Run k6 smoke tests
-        #       env:
-        #           URL: ${{ secrets.SMOKE_TEST_PERF_URL }}
-        #           HOST: ${{ secrets.SMOKE_TEST_PERF_HOST }}
-        #           A_USER: ${{ secrets.SMOKE_TEST_PERF_ADMIN_USER }}
-        #           A_PW: ${{ secrets.SMOKE_TEST_PERF_ADMIN_PASSWORD }}
-        #           C_USER: ${{ secrets.SMOKE_TEST_PERF_ADMIN_USER }}
-        #           C_PW: ${{ secrets.SMOKE_TEST_PERF_ADMIN_PASSWORD }}
-        #           P_ID: 22733
-        #       run: |
-        #           ./k6 run plugins/woocommerce/tests/performance/tests/gh-action-daily-ext-requests.js
+    #     - name: Run k6 smoke tests
+    #       env:
+    #           URL: ${{ secrets.SMOKE_TEST_PERF_URL }}
+    #           HOST: ${{ secrets.SMOKE_TEST_PERF_HOST }}
+    #           A_USER: ${{ secrets.SMOKE_TEST_PERF_ADMIN_USER }}
+    #           A_PW: ${{ secrets.SMOKE_TEST_PERF_ADMIN_PASSWORD }}
+    #           C_USER: ${{ secrets.SMOKE_TEST_PERF_ADMIN_USER }}
+    #           C_PW: ${{ secrets.SMOKE_TEST_PERF_ADMIN_PASSWORD }}
+    #           P_ID: 22733
+    #       run: |
+    #           ./k6 run plugins/woocommerce/tests/performance/tests/gh-action-daily-ext-requests.js
 
     test-plugins:
         name: Smoke tests on trunk with ${{ matrix.plugin }} plugin installed
@@ -184,16 +184,9 @@ jobs:
             contents: read
         # needs: [api-tests] # mytodo uncomment
         env:
-            # USE_WP_ENV: 1
+            USE_WP_ENV: 1
             ALLURE_RESULTS_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/e2e-pw/allure-results
             ALLURE_REPORT_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/e2e-pw/allure-report
-            ADMIN_PASSWORD: ${{ secrets.SMOKE_TEST_ADMIN_PASSWORD }}
-            ADMIN_USER: ${{ secrets.SMOKE_TEST_ADMIN_USER }}
-            ADMIN_USER_EMAIL: ${{ secrets.SMOKE_TEST_ADMIN_USER_EMAIL }}
-            BASE_URL: ${{ secrets.SMOKE_TEST_URL }}
-            CUSTOMER_PASSWORD: ${{ secrets.SMOKE_TEST_CUSTOMER_PASSWORD }}
-            CUSTOMER_USER: ${{ secrets.SMOKE_TEST_CUSTOMER_USER }}
-            DEFAULT_TIMEOUT_OVERRIDE: 120000
 
         strategy:
             fail-fast: false
@@ -223,14 +216,11 @@ jobs:
             - name: Setup WooCommerce Monorepo
               uses: ./.github/actions/setup-woocommerce-monorepo
               with:
-                  install-filters: woocommerce
-                  build: false
+                build-filters: woocommerce
 
-
-            # - name: Launch wp-env e2e environment
-            #   working-directory: plugins/woocommerce
-            #   run: pnpm env:test --filter=woocommerce
-            
+            - name: Launch wp-env e2e environment
+              working-directory: plugins/woocommerce
+              run: pnpm env:test --filter=woocommerce
 
             - name: Download and install Chromium browser.
               working-directory: plugins/woocommerce
@@ -244,11 +234,11 @@ jobs:
                   GITHUB_TOKEN: ${{ secrets.E2E_GH_TOKEN }}
               run: pnpm exec playwright test --config=tests/e2e-pw/playwright.config.js upload-plugin.spec.js
 
-            # - name: Run the rest of E2E tests
-            #   working-directory: plugins/woocommerce
-            #   env:
-            #       E2E_MAX_FAILURES: 15
-            #   run: pnpm exec playwright test --config=tests/e2e-pw/playwright.config.js
+            - name: Run the rest of E2E tests
+              working-directory: plugins/woocommerce
+              env:
+                  E2E_MAX_FAILURES: 15
+              run: pnpm exec playwright test --config=tests/e2e-pw/playwright.config.js basic.spec.js # mytodo remove basic
 
             - name: Generate E2E Test report.
               if: success() || failure()
